version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    working_dir: /frontend
    platform: linux/x86_64
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:5173"]
      timeout: 10s
      retries: 5
    volumes:
      - ./frontend/src:/frontend/src

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    working_dir: /backend
    # tty: true
    # # Mesmo que `docker run -i`
    # stdin_open: true
    # # Substitui o comando padrão da imagem do node
    # command: bash
    command: npm run start
    volumes:
    - ./backend/src:/backend/src
    platform: linux/x86_64
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      - JWT_SECRET=jwt_secret
      # db:
      - DB_USER=root
      - DB_PASS=root
      - DB_HOST=db
      - DB_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5

  db:
    image: mysql:8.0.21
    platform: linux/x86_64
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE # omite alertas menores