version: '3.9'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    working_dir: /frontend
    platform: linux/x86_64
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:5173"

    restart: always
    depends_on:
      - backend

  backend:
    container_name: backend
    build: ./backend
    working_dir: /backend
    # tty: true
    # # Mesmo que `docker run -i`
    # stdin_open: true
    # # Substitui o comando padrão da imagem do node
    # command: bash
    restart: always
    ports:
      - "3001:3001"
    volumes:
    - ./backend/src:/backend/src
    platform: linux/x86_64
    environment:
      - APP_PORT=3001
      - JWT_SECRET=jwt_secret
      # db:
      - DB_USER=root
      - DB_PASS=root
      - DB_HOST=db
      - DB_PORT=3306
      # - MONGO_URI=mongodb://mongodb:27017/CarShop
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:8.0
    platform: linux/x86_64
    ports:
      - 3306:3306
    volumes:
      - ./:/backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: 'always'
    cap_add:
      - SYS_NICE
  # db:
  #   container_name: db
  #   image: mongo:5.0.7
  #   platform: linux/x86_64
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./:/backend
  #   restart: 'always'
  #   cap_add:
  #     - SYS_NICE # Deve omitir alertas menores

networks:
  default:
    name: speed_help_net
